version: '2'
services:
  uniset:
    build:
      context: .
    image: unicef/uniset:dev
    command: odk
    ports:
      - "8080:${ODK_PORT}"
      - "8443:${ODK_PORT_SECURE}"
    depends_on:
      - db
    links:
      - db
    environment:
      - ODK_HOSTNAME
      - ODK_ADMIN_USER=admin
      - ODK_ADMIN_USERNAME=admin
      - ODK_AUTH_REALM
      - ODK_PORT
      - ODK_PORT_SECURE
      - DATABASE_URL
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - FLYWAY
      - ODK
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: odk
  adminer:
    image: adminer
    ports:
      - 8000:8080
